### PR TITLE
Change function to kiendesha and strings to tungo

### PR DESCRIPTION
**Pull request by BaharaJr**

### CODE REVIEW

**Comment by AvicennaJr** [comment]
Thank you, but Kiendesha and Tungo aren't terminologies used in Nuru and will probably confuse the user. I'm thinking we should make a more standardized way of writing error messages since the ones I wrote were in haste.

Do you think you can take the task of standardizing the error message throughout the language? We can have a discussion about it in the [Nuru groupchat](https://t.me/NuruProgrammingChat), this will allow getting input from others too.

**Comment by BaharaJr** [comment]
> I'm thinking we should make a more standardized way of writing error messages since the ones I wrote were in haste.
> 
> Do you think you can take the task of standardizing the error message throughout the language? We can have a discussion about it in the [Nuru groupchat](https://t.me/NuruProgrammingChat), this will allow getting input from others too.

Sure. Thanks.

**Comment by neicore** [comment]
hey @BaharaJr just a lil FYI; in the Docs we ended up calling Operators Viendeshi and Functions Vitendakazi

https://nyaraka.vercel.app/viendeshaji

https://nyaraka.vercel.app/vitendakazi

**Review by AvicennaJr — APPROVED** [review]

**Comment by BaharaJr** [comment]
> hey @BaharaJr just a lil FYI; in the Docs we ended up calling Operators Viendeshaji and Functions Vitendakazi
> 
> https://nyaraka.vercel.app/viendeshaji
> 
> https://nyaraka.vercel.app/vitendakazi

Thanks for the info @neicore

**Pull request merged**
